name: Deploy
on:
  workflow_dispatch
jobs:
  Build:
    uses: nareshgdevops/roboshop-github-actions/.github/workflows/aks-deploy.yml@main
    with:
      appName: 'user'
      appEnv: 'dev'
      resourceGroup: 'ukwest-dev'
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

